### ISSUE TITLE
Add unique 'User-Agent' header to http requests

### ISSUE THREAD

**Issue by phalt** [Oleur/SWAPI-Android-SDK#1]
Hi, could you add a unique 'User-Agent' header to the http requests that are sent with this helper library?

Set it to 'swapi-android' or similar. This will help me when diagnosing errors and tracking usages.

Thank you!

**Comment by Oleur** [comment]
User-Agent added in the latest commit.
I added "swapi-android-<AndroidReleaseName>" as the user-agent. For example a Lollipop device will give you: "swapi-android-5.0"

**Comment by phalt** [comment]
Perfect :+1:
